### ISSUE TITLE
Retain image upload feature?

### ISSUE THREAD

**Issue by le717** [newbthenewbd/grav-plugin-tinymce-editor#1]
I'm looking at implementing this plugin for a site I'm transitioning from WordPress to Grav, and so far I am liking it. However, it seems to disable the built-in Grav Admin image uploader. That's kinda an issue for me because my theme makes use of `{{ page.media.images|first }}` to display a sort of "hero image", and without that uploader, there's no way to do that. Is it possible to retain the image uploader with TinyMCE enabled?

Thanks!

**Comment by newbthenewbd** [comment]
I've thought about putting the file picker back in there once I figure out how to make it output HTML code rather than Markdown. My reasoning for that, though, was that it's much better than what TinyMCE offers (aka base64 images placed directly in the page's source) when one wants to place multiple same images on a page, or something that isn't an image at all.

Thanks for giving another use case this may have and confirming the demand, added to the To Do section.

**Comment by le717** [comment]
Thanks for the update and workaround! I may just implement that workaround for the time being. :)

**Comment by newbthenewbd** [comment]
Implemented in v1.1.0.
