### ISSUE TITLE
Upload unminified code

### ISSUE THREAD

**Issue by Tamriel** [newbthenewbd/grav-plugin-tinymce-editor#19]
The heart of this plugin is the JavaScript code in line 22 of the file [tinymce.html.twig](https://github.com/newbthenewbd/grav-plugin-tinymce-editor/blob/develop/templates/forms/fields/tinymce/tinymce.html.twig#L22).
Please share an unminified version of it, so other people are able to read and extend it.

**Comment by newbthenewbd** [comment]
Unfortunately I don't have a version like that, as I manually edit the manually since-ever-minified code :slightly_smiling_face:

I suppose a tool like [https://www.unminifier.com/](https://www.unminifier.com/) might help a bit, although the Twig mess needs manual fixing afterwards, that being one of the reasons as to why my minifying is manual.
