### ISSUE TITLE
Bug in TinyMCE Editor Integration v1.2.0 with Grav 1.5.1 + Gantry v5.4.26

### ISSUE THREAD

**Issue by Legolasindar** [newbthenewbd/grav-plugin-tinymce-editor#24]
**GRAV:** 1.5.1
**GANTRY:** 5.4.26
**TinyMCE Editor Integration:** 1.2.0

My site works well, not problem. Today, i updated TinyMCE Editor Integration to 1.2.0 version, and after this, the Recompile CSS option of Gantry not works, say this:

```
500 Internal Server Error
Oops, UniformResourceLocator: Absolute stream path with relative lookup not allowed ().
```

I tried disabling the TinyMCE plugin, and works again. I tried in another site in another hosting, and the same situation. Before uptade, works well, after update, nots works.

**Comment by newbthenewbd** [comment]
As serious as this issue sounds, I've been thus far unable to reproduce it. Are You possibly running Grav from within a subdirectory (i.e. `https://www.example.com/gravsite`)?

Thanks for reporting!

**Comment by newbthenewbd** [comment]
Inspired by this report to look again at the code, I've just released v1.2.1, ought to improve how the absolute URL generator works for the Grav installs not directly located in webroot. However, the release is rather unlikely to solve this problem, as I'm honestly still quite clueless as to what it might be caused by.

Could You please assemble a minimal Grav install exhibiting this problem, and share a backup of it? If v1.2.1 hasn't somehow fixed the issue, I'm afraid that I might not be able to trace it soon without getting such install into my hands.

**Comment by Legolasindar** [comment]
With a fresh install i cant reproduce this bug. But i dont know what happen, because only appear this error in my web with your plugin.

**Comment by newbthenewbd** [comment]
While I am still unable to determine the exact source of the problem, the improvements introduced in v1.2.2 are likely to affect it. Could You please check whether the issue persists in that version?

Thanks!

**Comment by Legolasindar** [comment]
The problem not appear now. It seems that it is fixed. Nice works, thanks 👍 :)
