### ISSUE TITLE
[BUG] Boolean values in plugin admin config page are saved and treated as strings 

### ISSUE THREAD

**Issue by nned** [newbthenewbd/grav-plugin-tinymce-editor#4]
To reproduce - add some config setting to parameters section, and type in value field :  _false_ or _0_
After that, on page editing we can see in developer tools, this value in **object tinyMCE.editors[0].settings.** is set to string  _'false'_ or string _'0'_
String _'false'_ (or _'0'_) evaluates to _true_ in js, so we get undesired behavior.

As workaround, to make parameter false - you can leave empty field, which transforms in '' (empty string), which evaluates to false later.

**Comment by newbthenewbd** [comment]
Actually, `'0' == false` returns true in JavaScript, while only `'0' === false` returns false, with `'0' === true` returning false too. According to my quick test, however, the issue indeed exists. (could it be TinyMCE simply dismissing empty parameters, and considering non-boolean others to be true? [The documentation](https://www.tinymce.com/docs/plugins/paste/#paste_data_images) is rather vague...)

Because the parameters section is one that doesn't exactly know what's entered into it, this will however be hacky to fix - the only idea I'm having right now is to make Twig automatically patch the `0` and `false` inputs, which is what I guess I'm going to do.

Thanks for reporting!

**Comment by newbthenewbd** [comment]
Fixed in v1.1.2, now let's just wait for those who randomly needed their `false` or `0` to be a string...
