### ISSUE TITLE
API key warning

### ISSUE THREAD

**Issue by alexeych** [newbthenewbd/grav-plugin-tinymce-editor#47]
The following warning pops up everytime TinyMCE editor is loaded
> The API key you have entered is invalid. Please review your API key here

**Comment by newbthenewbd** [comment]
This warning is supposed to pop up when an invalid API key is entered into the plugin's config. When no API key is entered, as is default, a local copy of the editor is used, rather than fetched from the cloud.

Are You sure that the API key field in the plugin's config at `user/config/plugins/tinymce-editor.yaml` is empty (i.e. `apikey: ''`), or if You actually want to use the cloud-hosted version of TinyMCE (e.g. to make use of the paid plugins), that the key has been entered correctly? If an URL address is provided, it should not be copied in its entirety, but the key should be extracted from it.

**Comment by alexeych** [comment]
OK. I've installed the plugin via admin UI and didn't see the API key field.

**Comment by newbthenewbd** [comment]
Actually, I've only now found that this is absolutely a real issue - looks like getgrav/grav@864a938f8de9cec1c977e4986b08012fdcba9ced ricocheted on us, with `null` API key not resolving to `""`... So, derp - to be fixed soon... :upside_down_face:

Thanks for reporting!

**Comment by newbthenewbd** [comment]
Fixed in v1.3.0.
