### ISSUE TITLE
Use Grav native media system

### ISSUE THREAD

**Issue by titoko** [newbthenewbd/grav-plugin-tinymce-editor#5]
Hi, I'm currently looking on how to fallback on native Grav media system to allow the user to use action like crop, cropresize etc ... (https://learn.getgrav.org/content/media)

I have 2 idea on that  :

- create à tinymce plugin that extent the image one and who will insert an markdown img tag (instead of the html one)

or

- extend Parsedown to parse the img tag from the current tinymce.

I let you know if I have a working POC

**Comment by newbthenewbd** [comment]
Honestly, I don't quite understand what functionality You would like added, as the [image actions](https://learn.getgrav.org/content/media#image-actions) themselves seem to work just fine.

You can apply an action to an image by uploading the image with the use of the native Grav file picker, clicking the Insert button (the one with a + icon) next to the image and appending the image action under `Source`, so that under **Tools** > **Source code** the resulting tag looks similar to this:
```
<img src="some-page/image.png?negate" alt="" width="123" height="456" />
```
Since I may have likely understood something wrongly, I'm keeping the issue open for now and request elaboration.

**Comment by titoko** [comment]
Well this is what I was looking for but never tought to just try...
So closing the issues 

Thanks
