### ISSUE TITLE
Floating elements?

### ISSUE THREAD

**Issue by Krachbummente1337** [newbthenewbd/grav-plugin-tinymce-editor#8]
Hey there,

is it possible to align pictures as floating elements next to the text without having them stick directly together? I haven't found an option to add some margin between both, yet.
I am also concerned with the responsibility for mobile devices with such elements.

Is there an elegant way to solve that issue? :)

Yours sincrely,
_KBE._

**Comment by newbthenewbd** [comment]
An elegant way to do this would be to modify the theme's (S)CSS, so that the `img` elements have a `margin`. Note that the result wouldn't be visible in the editor, at least until I duplicate what [this fork](https://github.com/swunderer/grav-plugin-tinymce-editor) has accomplished or get a pull request.

If that's not feasible, there are multiple blocks You can place the image inside from within TinyMCE, under **Formats** > **Blocks**. If at least one of them has a margin in Your theme's (S)CSS, that might work for You.

If that isn't feasible either, You can just go to **Tools** > **Source code**, and add a margin to the CSS of the `img` element, like this:
`<p><img style="float: right; margin: 15px;" src="test/test.png" width="123" height="456" />Insert random very long text here</p>`

As for the responsive design, that depends on the theme's CSS and/or JavaScript - y'know, TinyMCE isn't usually the thing that turns `about:blank` into a full-fledged company website, but just a page editor... :smile:

**Comment by Krachbummente1337** [comment]
Thank you very much for that information! :)
